version: '3.5'
services:
  flyway:
    container_name: flyway
    image: flyway/flyway:9-alpine #9-alpine?
    command: -url=jdbc:postgresql://flyway-pg/lab_2 -connectRetries=60 -user=postgres -password=password validate
    volumes:
      - ./migrations:/flyway/sql
    networks:
      - default
networks:
  default:
    external:
      name: flywaynet