version: '3.5'
services:
  flyway-pg:
    container_name: flyway-pg
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./entrypoint-scripts:/docker-entrypoint-initdb.d/
    networks:
      - default
networks:
  default:
    name: flywaynet
    driver: bridge